### ISSUE TITLE
Missing PlatformIO installation is not detected

### ISSUE THREAD

**Issue by enoy19** [nexoscp/PlatformIOLion#23]
When executing gradle task `intellij > runIde` and creating a platformIO project, an error occurs when selecting a board. It just silently fails.

Stacktrace
`11:22:50 AM: Executing task 'runIde'...

> Task :compileKotlin UP-TO-DATE
> Task :compileJava UP-TO-DATE
> Task :patchPluginXml UP-TO-DATE
> Task :processResources UP-TO-DATE
> Task :classes UP-TO-DATE
> Task :inspectClassesForKotlinIC
> Task :instrumentCode UP-TO-DATE
> Task :postInstrumentCode
> Task :jar UP-TO-DATE
> Task :prepareSandbox
Download https://cache-redirector.jetbrains.com/jetbrains.bintray.com/intellij-jbr/jbr-11_0_3-linux-x64-b304.10.tar.gz
> Task :runIde
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.intellij.ide.ClassUtilCore to field sun.net.www.protocol.jar.JarFileFactory.fileCache
WARNING: Please consider reporting this to the maintainers of com.intellij.ide.ClassUtilCore
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2019-11-26 11:24:27,177 [   7772]   WARN - j.internal.DebugAttachDetector - Unable to start DebugAttachDetector, please add `--add-exports=java.base/jdk.internal.vm=ALL-UNNAMED` to VM options 
2019-11-26 11:24:28,754 [   9349]   WARN - s.impl.EditorColorsManagerImpl - Cannot find scheme: VibrantInk from plugin: com.intellij.database 
2019-11-26 11:24:28,754 [   9349]   WARN - s.impl.EditorColorsManagerImpl - Cannot find scheme: WarmNeon from plugin: com.intellij.database 
2019-11-26 11:24:28,754 [   9349]   WARN - s.impl.EditorColorsManagerImpl - Cannot find scheme: High сontrast from plugin: com.intellij.database 
2019-11-26 11:24:32,255 [  12850]   WARN - til.ui.update.LazyUiDisposable - use application as a parent disposable 
2019-11-26 11:24:33,735 [  14330]   WARN - til.ui.update.LazyUiDisposable - use application as a parent disposable 
2019-11-26 11:24:35,055 [  15650]  ERROR - llij.ide.plugins.PluginManager - null 
java.security.PrivilegedActionException: java.security.PrivilegedActionException: java.util.concurrent.ExecutionException: com.intellij.execution.process.ProcessNotCreatedException: Cannot run program "platformio": error=2, No such file or directory
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:873)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:818)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:461)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:704)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:460)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.security.PrivilegedActionException: java.util.concurrent.ExecutionException: com.intellij.execution.process.ProcessNotCreatedException: Cannot run program "platformio": error=2, No such file or directory
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	... 14 more
Caused by: java.util.concurrent.ExecutionException: com.intellij.execution.process.ProcessNotCreatedException: Cannot run program "platformio": error=2, No such file or directory
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at platformio.services.impl.CommandLinePlatformIOService.loadAllBoards(CommandLinePlatformIOService.kt:40)
	at platformio.project.ui.NewPIOProjectSettingsForm.lambda$new$1(NewPIOProjectSettingsForm.java:32)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6651)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6416)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5026)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	... 19 more
Caused by: com.intellij.execution.process.ProcessNotCreatedException: Cannot run program "platformio": error=2, No such file or directory
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:412)
	at com.intellij.execution.process.OSProcessHandler.startProcess(OSProcessHandler.java:45)
	at com.intellij.execution.process.OSProcessHandler.<init>(OSProcessHandler.java:38)
	at com.intellij.execution.process.CapturingProcessHandler.<init>(CapturingProcessHandler.java:21)
	at platformio.services.impl.CommandLinePlatformIOService$loadBoardsInternal$1.call(CommandLinePlatformIOService.kt:46)
	at platformio.services.impl.CommandLinePlatformIOService$loadBoardsInternal$1.call(CommandLinePlatformIOService.kt:29)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.IOException: Cannot run program "platformio": error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at com.intellij.execution.configurations.GeneralCommandLine.startProcess(GeneralCommandLine.java:443)
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:408)
	... 9 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	... 12 more
2019-11-26 11:24:35,065 [  15660]  ERROR - llij.ide.plugins.PluginManager - CLion 2019.2  Build #CL-192.5728.100 
2019-11-26 11:24:35,066 [  15661]  ERROR - llij.ide.plugins.PluginManager - JDK: 11.0.3; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o 
2019-11-26 11:24:35,066 [  15661]  ERROR - llij.ide.plugins.PluginManager - OS: Linux 
2019-11-26 11:24:35,073 [  15668]  ERROR - llij.ide.plugins.PluginManager - Plugin to blame: PlatformIO version: 0.2 
`

**Comment by sith** [comment]
Did you install platfromio CLI?

**Comment by enoy19** [comment]
It wasn't installed.
there might be a misunderstanding. It's clear that it failed because platformio cli wasn't installed. It would be great if the plugin informs you about that and does not fail in the background without giving any feedback.

**Comment by sith** [comment]
Agree. We will fix it.

**Comment by sith** [comment]
I pushed fix

**Comment by nexoscp** [comment]
Nice solution!

**Comment by enoy19** [comment]
I'll close this issue then. Thank you @sith
